# Generated by Django 4.2 on 2023-04-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pubilsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='发行商')),
                ('email', models.EmailField(max_length=16, verbose_name='电子邮件')),
            ],
        ),
    ]
