# Generated by Django 3.2.18 on 2023-04-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='书籍名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
            ],
        ),
    ]
