# Generated by Django 4.2 on 2023-04-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='学生姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
        ),
    ]
